using System.IO;
using NUnit.Framework;
using UnityEngine;

namespace Grenaders.Editor.CodeGeneration.MyCodeGenerators
{
    public abstract class BaseCodeGenerator
    {
        public const string Path = "Assets\\Scripts\\AutoGenerated";

        public abstract string FileName();
        public abstract string Code();

        public virtual string Folder()
        {
            return string.Empty;
        }


        public void Generate()
        {
            if (!Directory.Exists(Path))
            {
                Directory.CreateDirectory(Path);
            }

            var folder = Folder();
            var fileName = FileName()+".cs";

            var filePath = $"{Path}";

            if (!folder.Equals(string.Empty)) filePath   += $"\\{folder}";
            if (!fileName.Equals(string.Empty)) filePath += $"\\{fileName}";

            using FileStream stream = new FileStream(filePath, FileMode.OpenOrCreate, FileAccess.Write);
            using StreamWriter writer = new StreamWriter(stream);
            writer.Write(Code());
            Debug.Log($"Generated in {this.GetType().FullName}");
        }
    }
}